### ISSUE TITLE
Work Plan

### ISSUE THREAD

**Issue by johnkord** [johnkord/rs-downloader#1]
- [ ] Use crypto APIs for payload encryption instead of OpenSSL at the command line
- [ ] Improve error handling
- [ ] Get an official build of azure-storage-azcopy for each platform (the armv7 version isn't officially available, and is pretty buggy!)
- [ ] Support other storage services
- [ ] Allow encryption to be optionally disabled
- [ ] Logging options
- [ ] Support downloading a list/heirarchy of files and then uploading them as a directory
